name: Maven CI + CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Test
    uses: ./.github/workflows/action.yaml
    with:
        required: "required-value"
        optional: "optional-value"